name: Pull-request CI
run-name: ${{ github.actor }} run these jobs
on: [pull_request]

jobs:
  build-che:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v2.3.1

      - name: Set environment varialbles
        env:
          REACT_APP_API_BASE_URL: ${{secrets.REACT_APP_API_BASE_URL}}
        run: echo "Variables successfully set"

      - name: Install depencies
        run: npm ci

      - name: Linting
        run: npm run lint --strict

      - name: Install and Build
        # env:
        #   REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL}}
        run: npm run build

      - name: Testing
        run: npm run test
