name: Pull-request CI
run-name: ${{ github.actor }} run these jobs
on: [pull_request]

jobs:
  build-che:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v2.3.1

      - name: Linting
        run: npm run lint

      - name: Install and Build
        env:
          REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL}}
        run: |
          npm ci
          npm run build

      - name: Testing
        run: npm run test
